language: java
jdk:
  - openjdk8

branches:
  only:
    - master

# Travis CI 서버의 홈
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.gradle'

script: "./gradlew clean build"

before_deploy:
  - zip -r study-springboot2-webservice
  - mkdir -p deploy
  - mv study-springboot2-webservice.zip deploy/study-springboot2-webservice.zip

deploy:
  - provider: s3
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET-KEY
    bucket: study-springboot-build #S3 버킷
    region: ap-northeast-2
    skip_cleanup: true
    acl: private # zip 파일 접근을 private
    local_dir: deploy # before_deploy에서 생성한 dir
    wait-until-deployed : true

# CI 실행 완료 시 메일로 알람
notifications:
  email:
    recipients:
      - daul@kookmin.ac.kr